Evaluation/Evaluation/Controllers/AdminController.cs
using Evaluation.Data;
using Evaluation.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Evaluation.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Logout()
        {
            return new RedirectResult(url: "/Registration/Login", permanent: true, preserveMethod: true);
        }

        public IActionResult Index()
        {
            var objRegistrations = _context.Registrations.ToList();

            return View(objRegistrations);
        }

        public async Task<IActionResult> AssignSalary(int user_id)
        {
            if (user_id == 0)
            {
                return NotFound();
            }

            var joinedData = await (from t1 in _context.Registrations
                                    where t1.user_id == user_id
                                    select new SalaryViewModel
                                    {
                                        user_id = t1.user_id,
                                        name = t1.name,
                                        dob = t1.dob,
                                        gender = t1.gender,
                                        account_type = t1.account_type,
                                        email = t1.email,
                                        password = t1.password,
                                        photo_name = t1.photo_name,
                                        photo_path = t1.photo_path,

                                        // salary fields left empty (to be assigned later)
                                        salary_id = 0,
                                        month = "",
                                        year = 0,
                                        salary = 0
                                    }).FirstOrDefaultAsync();


            if (joinedData == null)
            {
                return NotFound();
            }

            return View(joinedData); 
        }

        [HttpPost]
        public async Task<IActionResult> SalaryAllocation(SalaryViewModel obj)
        {
            var salary = new Salary
            {
                user_id = obj.user_id,
                month = obj.month,
                year = obj.year,
                salary = obj.salary
            };

            _context.salaries.Add(salary);
            await _context.SaveChangesAsync();

            TempData["message"] = "Salary allocated successfully!";
            return RedirectToAction("AssignSalary", new { user_id = obj.user_id });
        }

        public IActionResult Profile()
        {
            int? id = HttpContext.Session.GetInt32("user_ID");
            var user = _context.Registrations.Find(id);
            return View(user);
        }
    }
}

Evaluation/Evaluation/Controllers/StaffController.cs
using Evaluation.Data;
using Evaluation.Models;
using Microsoft.AspNetCore.Mvc;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Evaluation.Controllers
{
    public class StaffController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _iweb;


        public StaffController(ApplicationDbContext context, IWebHostEnvironment iweb)
        {
            _context = context;
            _iweb = iweb;
        }
        public IActionResult Logout()
        {
            return new RedirectResult(url: "/Registration/Login", permanent: true, preserveMethod: true);
        }

        public IActionResult Index()
        {
            int? id = HttpContext.Session.GetInt32("user_ID");
            var user = _context.Registrations.Find(id);
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProfile(IFormFile img_file, Registration obj)
        {
            if (!ModelState.IsValid)
            {
                return View(obj);
            }

            var existingUser = await _context.Registrations.FindAsync(obj.user_id);
            if (existingUser == null)
            {
                return NotFound();
            }

            existingUser.name = obj.name;
            existingUser.dob = obj.dob;
            existingUser.gender = obj.gender;
            existingUser.account_type = obj.account_type;
            existingUser.email = obj.email;
            existingUser.password = obj.password;

            if (img_file != null && img_file.Length > 0)
            {
                var extension = Path.GetExtension(img_file.FileName).ToLower();
                if (extension == ".jpg" || extension == ".gif" || extension == ".png")
                {
                    var uploadPath = Path.Combine(_iweb.WebRootPath, "images", img_file.FileName);

                    using (var stream = new FileStream(uploadPath, FileMode.Create))
                    {
                        await img_file.CopyToAsync(stream);
                    }

                    existingUser.photo_name = img_file.FileName;
                    existingUser.photo_path = uploadPath;
                }
            }

            _context.Update(existingUser);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public IActionResult Report()
        {
            int? id = HttpContext.Session.GetInt32("user_ID");

            var salaries = _context.salaries
                                   .Where(s => s.user_id == id)
                                   .ToList();

            return View(salaries);  
        }

    }
}

Evaluation/Evaluation/Views/Shared/Admin_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Evaluation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Evaluation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active">
                                All Staffs List
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="Profile">My Profile</a>
                        </li>
                        </li>
                    </ul>
                    <div class="d-flex mr-5">
                        <form class="d-flex ms-auto">
                            <a class="btn btn-secondary my-2 my-sm-0" type="submit" asp-controller="Admin" asp-action="Logout">Logout</a>
                        </form>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Evaluation/Evaluation/Views/Shared/Staff_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Evaluation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Evaluation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3"> *@
        @*     <div class="container-fluid"> *@
        @*         <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Evaluation</a> *@
        @*         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" *@
        @*                 aria-expanded="false" aria-label="Toggle navigation"> *@
        @*             <span class="navbar-toggler-icon"></span> *@
        @*         </button> *@
        @*         <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"> *@
        @*             <ul class="navbar-nav flex-grow-1"> *@
        @*                 <li class="nav-item"> *@
        @*                     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
        @*                 </li> *@
        @*                 <li class="nav-item"> *@
        @*                     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
        @*                 </li> *@
        @*             </ul> *@
        @*         </div> *@
        @*     </div> *@
        @* </nav> *@

        <nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-controller="Staff" asp-action="Index">
                                My Profile
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Staff" asp-action="Report">Salary Report</a>
                        </li>
                    </ul>
                    <div class="d-flex mr-5">
                        <form class="d-flex ms-auto">
                            <a class="btn btn-secondary my-2 my-sm-0" type="submit" asp-controller="Staff" asp-action="Logout">Logout</a>
                        </form>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Evaluation/Evaluation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - sessions</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/sessions.styles.css" asp-append-version="true" />
</head>
<body>
    <header>

    </header>
    <div class="container-fluid d-flex justify-content-center mt-5">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>